/*
 * HiddenLayer ModelScan V2
 * HiddenLayer ModelScan API for scanning of models
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Objects;
import java.util.StringJoiner;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Represents a directed edge in a graph.
 */
@JsonPropertyOrder({
    Edge.JSON_PROPERTY_ID,
    Edge.JSON_PROPERTY_LABEL,
    Edge.JSON_PROPERTY_SOURCE_NODE_ID,
    Edge.JSON_PROPERTY_TARGET_NODE_ID,
    Edge.JSON_PROPERTY_PROPERTIES
})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2024-12-03T15:49:05.899737Z[GMT]",
        comments = "Generator version: 7.6.0")
public class Edge {
    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public static final String JSON_PROPERTY_LABEL = "label";
    private JsonNullable<Message> label = JsonNullable.<Message>undefined();

    public static final String JSON_PROPERTY_SOURCE_NODE_ID = "sourceNodeId";
    private String sourceNodeId;

    public static final String JSON_PROPERTY_TARGET_NODE_ID = "targetNodeId";
    private String targetNodeId;

    public static final String JSON_PROPERTY_PROPERTIES = "properties";
    private PropertyBag properties;

    public Edge() {}

    public Edge id(String id) {
        this.id = id;
        return this;
    }

    /**
     * A string that uniquely identifies the edge within its graph.
     * @return id
     **/
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(String id) {
        this.id = id;
    }

    public Edge label(Message label) {
        this.label = JsonNullable.<Message>of(label);
        return this;
    }

    /**
     * Get label
     * @return label
     **/
    @javax.annotation.Nullable
    @JsonIgnore
    public Message getLabel() {
        return label.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_LABEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public JsonNullable<Message> getLabel_JsonNullable() {
        return label;
    }

    @JsonProperty(JSON_PROPERTY_LABEL)
    public void setLabel_JsonNullable(JsonNullable<Message> label) {
        this.label = label;
    }

    public void setLabel(Message label) {
        this.label = JsonNullable.<Message>of(label);
    }

    public Edge sourceNodeId(String sourceNodeId) {
        this.sourceNodeId = sourceNodeId;
        return this;
    }

    /**
     * Identifies the source node (the node at which the edge starts).
     * @return sourceNodeId
     **/
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_SOURCE_NODE_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getSourceNodeId() {
        return sourceNodeId;
    }

    @JsonProperty(JSON_PROPERTY_SOURCE_NODE_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSourceNodeId(String sourceNodeId) {
        this.sourceNodeId = sourceNodeId;
    }

    public Edge targetNodeId(String targetNodeId) {
        this.targetNodeId = targetNodeId;
        return this;
    }

    /**
     * Identifies the target node (the node at which the edge ends).
     * @return targetNodeId
     **/
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_TARGET_NODE_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getTargetNodeId() {
        return targetNodeId;
    }

    @JsonProperty(JSON_PROPERTY_TARGET_NODE_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setTargetNodeId(String targetNodeId) {
        this.targetNodeId = targetNodeId;
    }

    public Edge properties(PropertyBag properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get properties
     * @return properties
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public PropertyBag getProperties() {
        return properties;
    }

    @JsonProperty(JSON_PROPERTY_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProperties(PropertyBag properties) {
        this.properties = properties;
    }

    /**
     * Return true if this edge object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Edge edge = (Edge) o;
        return Objects.equals(this.id, edge.id)
                && equalsNullable(this.label, edge.label)
                && Objects.equals(this.sourceNodeId, edge.sourceNodeId)
                && Objects.equals(this.targetNodeId, edge.targetNodeId)
                && Objects.equals(this.properties, edge.properties);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b
                || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, hashCodeNullable(label), sourceNodeId, targetNodeId, properties);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Edge {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    label: ").append(toIndentedString(label)).append("\n");
        sb.append("    sourceNodeId: ").append(toIndentedString(sourceNodeId)).append("\n");
        sb.append("    targetNodeId: ").append(toIndentedString(targetNodeId)).append("\n");
        sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `id` to the URL query string
        if (getId() != null) {
            joiner.add(String.format(
                    "%sid%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getId()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `label` to the URL query string
        if (getLabel() != null) {
            joiner.add(getLabel().toUrlQueryString(prefix + "label" + suffix));
        }

        // add `sourceNodeId` to the URL query string
        if (getSourceNodeId() != null) {
            joiner.add(String.format(
                    "%ssourceNodeId%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getSourceNodeId()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `targetNodeId` to the URL query string
        if (getTargetNodeId() != null) {
            joiner.add(String.format(
                    "%stargetNodeId%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getTargetNodeId()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `properties` to the URL query string
        if (getProperties() != null) {
            joiner.add(String.format(
                    "%sproperties%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getProperties()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        return joiner.toString();
    }
}
