/*
 * HiddenLayer ModelScan V2
 * HiddenLayer ModelScan API for scanning of models
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Describes a runtime exception encountered during the execution of an analysis tool.
 */
@JsonPropertyOrder({
    Exception.JSON_PROPERTY_KIND,
    Exception.JSON_PROPERTY_MESSAGE,
    Exception.JSON_PROPERTY_STACK,
    Exception.JSON_PROPERTY_INNER_EXCEPTIONS,
    Exception.JSON_PROPERTY_PROPERTIES
})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2024-12-03T15:49:05.899737Z[GMT]",
        comments = "Generator version: 7.6.0")
public class Exception {
    public static final String JSON_PROPERTY_KIND = "kind";
    private String kind;

    public static final String JSON_PROPERTY_MESSAGE = "message";
    private String message;

    public static final String JSON_PROPERTY_STACK = "stack";
    private Stack stack;

    public static final String JSON_PROPERTY_INNER_EXCEPTIONS = "innerExceptions";
    private List<Exception> innerExceptions = new ArrayList<>();

    public static final String JSON_PROPERTY_PROPERTIES = "properties";
    private PropertyBag properties;

    public Exception() {}

    public Exception kind(String kind) {
        this.kind = kind;
        return this;
    }

    /**
     * A string that identifies the kind of exception, for example, the fully qualified type name of an object that was thrown, or the symbolic name of a signal.
     * @return kind
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_KIND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getKind() {
        return kind;
    }

    @JsonProperty(JSON_PROPERTY_KIND)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKind(String kind) {
        this.kind = kind;
    }

    public Exception message(String message) {
        this.message = message;
        return this;
    }

    /**
     * A message that describes the exception.
     * @return message
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getMessage() {
        return message;
    }

    @JsonProperty(JSON_PROPERTY_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMessage(String message) {
        this.message = message;
    }

    public Exception stack(Stack stack) {
        this.stack = stack;
        return this;
    }

    /**
     * Get stack
     * @return stack
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STACK)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Stack getStack() {
        return stack;
    }

    @JsonProperty(JSON_PROPERTY_STACK)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStack(Stack stack) {
        this.stack = stack;
    }

    public Exception innerExceptions(List<Exception> innerExceptions) {
        this.innerExceptions = innerExceptions;
        return this;
    }

    public Exception addInnerExceptionsItem(Exception innerExceptionsItem) {
        if (this.innerExceptions == null) {
            this.innerExceptions = new ArrayList<>();
        }
        this.innerExceptions.add(innerExceptionsItem);
        return this;
    }

    /**
     * An array of exception objects each of which is considered a cause of this exception.
     * @return innerExceptions
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_INNER_EXCEPTIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<Exception> getInnerExceptions() {
        return innerExceptions;
    }

    @JsonProperty(JSON_PROPERTY_INNER_EXCEPTIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setInnerExceptions(List<Exception> innerExceptions) {
        this.innerExceptions = innerExceptions;
    }

    public Exception properties(PropertyBag properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get properties
     * @return properties
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public PropertyBag getProperties() {
        return properties;
    }

    @JsonProperty(JSON_PROPERTY_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProperties(PropertyBag properties) {
        this.properties = properties;
    }

    /**
     * Return true if this exception object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Exception exception = (Exception) o;
        return Objects.equals(this.kind, exception.kind)
                && Objects.equals(this.message, exception.message)
                && Objects.equals(this.stack, exception.stack)
                && Objects.equals(this.innerExceptions, exception.innerExceptions)
                && Objects.equals(this.properties, exception.properties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(kind, message, stack, innerExceptions, properties);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Exception {\n");
        sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    stack: ").append(toIndentedString(stack)).append("\n");
        sb.append("    innerExceptions: ")
                .append(toIndentedString(innerExceptions))
                .append("\n");
        sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `kind` to the URL query string
        if (getKind() != null) {
            joiner.add(String.format(
                    "%skind%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getKind()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `message` to the URL query string
        if (getMessage() != null) {
            joiner.add(String.format(
                    "%smessage%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getMessage()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `stack` to the URL query string
        if (getStack() != null) {
            joiner.add(getStack().toUrlQueryString(prefix + "stack" + suffix));
        }

        // add `innerExceptions` to the URL query string
        if (getInnerExceptions() != null) {
            for (int i = 0; i < getInnerExceptions().size(); i++) {
                if (getInnerExceptions().get(i) != null) {
                    joiner.add(getInnerExceptions()
                            .get(i)
                            .toUrlQueryString(String.format(
                                    "%sinnerExceptions%s%s",
                                    prefix,
                                    suffix,
                                    "".equals(suffix)
                                            ? ""
                                            : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
                }
            }
        }

        // add `properties` to the URL query string
        if (getProperties() != null) {
            joiner.add(String.format(
                    "%sproperties%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getProperties()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        return joiner.toString();
    }
}
