/*
 * HiddenLayer ModelScan V2
 * HiddenLayer ModelScan API for scanning of models
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Contains information that enables a SARIF consumer to locate the external property file that contains the value of an externalized property associated with the run.
 */
@JsonPropertyOrder({
    ExternalPropertyFileReference.JSON_PROPERTY_LOCATION,
    ExternalPropertyFileReference.JSON_PROPERTY_GUID,
    ExternalPropertyFileReference.JSON_PROPERTY_ITEM_COUNT,
    ExternalPropertyFileReference.JSON_PROPERTY_PROPERTIES
})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2024-12-03T15:49:05.899737Z[GMT]",
        comments = "Generator version: 7.6.0")
public class ExternalPropertyFileReference {
    public static final String JSON_PROPERTY_LOCATION = "location";
    private ArtifactLocation location;

    public static final String JSON_PROPERTY_GUID = "guid";
    private String guid;

    public static final String JSON_PROPERTY_ITEM_COUNT = "itemCount";
    private Integer itemCount = -1;

    public static final String JSON_PROPERTY_PROPERTIES = "properties";
    private PropertyBag properties;

    public ExternalPropertyFileReference() {}

    public ExternalPropertyFileReference location(ArtifactLocation location) {
        this.location = location;
        return this;
    }

    /**
     * Get location
     * @return location
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public ArtifactLocation getLocation() {
        return location;
    }

    @JsonProperty(JSON_PROPERTY_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLocation(ArtifactLocation location) {
        this.location = location;
    }

    public ExternalPropertyFileReference guid(String guid) {
        this.guid = guid;
        return this;
    }

    /**
     * A stable, unique identifier for the external property file in the form of a GUID.
     * @return guid
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_GUID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getGuid() {
        return guid;
    }

    @JsonProperty(JSON_PROPERTY_GUID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGuid(String guid) {
        this.guid = guid;
    }

    public ExternalPropertyFileReference itemCount(Integer itemCount) {
        this.itemCount = itemCount;
        return this;
    }

    /**
     * A non-negative integer specifying the number of items contained in the external property file.
     * minimum: -1
     * @return itemCount
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ITEM_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getItemCount() {
        return itemCount;
    }

    @JsonProperty(JSON_PROPERTY_ITEM_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setItemCount(Integer itemCount) {
        this.itemCount = itemCount;
    }

    public ExternalPropertyFileReference properties(PropertyBag properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get properties
     * @return properties
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public PropertyBag getProperties() {
        return properties;
    }

    @JsonProperty(JSON_PROPERTY_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProperties(PropertyBag properties) {
        this.properties = properties;
    }

    /**
     * Return true if this externalPropertyFileReference object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExternalPropertyFileReference externalPropertyFileReference = (ExternalPropertyFileReference) o;
        return Objects.equals(this.location, externalPropertyFileReference.location)
                && Objects.equals(this.guid, externalPropertyFileReference.guid)
                && Objects.equals(this.itemCount, externalPropertyFileReference.itemCount)
                && Objects.equals(this.properties, externalPropertyFileReference.properties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(location, guid, itemCount, properties);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ExternalPropertyFileReference {\n");
        sb.append("    location: ").append(toIndentedString(location)).append("\n");
        sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
        sb.append("    itemCount: ").append(toIndentedString(itemCount)).append("\n");
        sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        return joiner.toString();
    }
}
