/*
 * HiddenLayer ModelScan V2
 * HiddenLayer ModelScan API for scanning of models
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Objects;
import java.util.StringJoiner;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Information that describes a run&#39;s identity and role within an engineering system process.
 */
@JsonPropertyOrder({
    RunAutomationDetails.JSON_PROPERTY_DESCRIPTION,
    RunAutomationDetails.JSON_PROPERTY_ID,
    RunAutomationDetails.JSON_PROPERTY_GUID,
    RunAutomationDetails.JSON_PROPERTY_CORRELATION_GUID,
    RunAutomationDetails.JSON_PROPERTY_PROPERTIES
})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2024-12-03T15:49:05.899737Z[GMT]",
        comments = "Generator version: 7.6.0")
public class RunAutomationDetails {
    public static final String JSON_PROPERTY_DESCRIPTION = "description";
    private JsonNullable<Message> description = JsonNullable.<Message>undefined();

    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public static final String JSON_PROPERTY_GUID = "guid";
    private String guid;

    public static final String JSON_PROPERTY_CORRELATION_GUID = "correlationGuid";
    private String correlationGuid;

    public static final String JSON_PROPERTY_PROPERTIES = "properties";
    private PropertyBag properties;

    public RunAutomationDetails() {}

    public RunAutomationDetails description(Message description) {
        this.description = JsonNullable.<Message>of(description);
        return this;
    }

    /**
     * Get description
     * @return description
     **/
    @javax.annotation.Nullable
    @JsonIgnore
    public Message getDescription() {
        return description.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public JsonNullable<Message> getDescription_JsonNullable() {
        return description;
    }

    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    public void setDescription_JsonNullable(JsonNullable<Message> description) {
        this.description = description;
    }

    public void setDescription(Message description) {
        this.description = JsonNullable.<Message>of(description);
    }

    public RunAutomationDetails id(String id) {
        this.id = id;
        return this;
    }

    /**
     * A hierarchical string that uniquely identifies this object&#39;s containing run object.
     * @return id
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(String id) {
        this.id = id;
    }

    public RunAutomationDetails guid(String guid) {
        this.guid = guid;
        return this;
    }

    /**
     * A stable, unique identifier for this object&#39;s containing run object in the form of a GUID.
     * @return guid
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_GUID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getGuid() {
        return guid;
    }

    @JsonProperty(JSON_PROPERTY_GUID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGuid(String guid) {
        this.guid = guid;
    }

    public RunAutomationDetails correlationGuid(String correlationGuid) {
        this.correlationGuid = correlationGuid;
        return this;
    }

    /**
     * A stable, unique identifier for the equivalence class of runs to which this object&#39;s containing run object belongs in the form of a GUID.
     * @return correlationGuid
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CORRELATION_GUID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getCorrelationGuid() {
        return correlationGuid;
    }

    @JsonProperty(JSON_PROPERTY_CORRELATION_GUID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCorrelationGuid(String correlationGuid) {
        this.correlationGuid = correlationGuid;
    }

    public RunAutomationDetails properties(PropertyBag properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get properties
     * @return properties
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public PropertyBag getProperties() {
        return properties;
    }

    @JsonProperty(JSON_PROPERTY_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProperties(PropertyBag properties) {
        this.properties = properties;
    }

    /**
     * Return true if this runAutomationDetails object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RunAutomationDetails runAutomationDetails = (RunAutomationDetails) o;
        return equalsNullable(this.description, runAutomationDetails.description)
                && Objects.equals(this.id, runAutomationDetails.id)
                && Objects.equals(this.guid, runAutomationDetails.guid)
                && Objects.equals(this.correlationGuid, runAutomationDetails.correlationGuid)
                && Objects.equals(this.properties, runAutomationDetails.properties);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b
                || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(hashCodeNullable(description), id, guid, correlationGuid, properties);
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RunAutomationDetails {\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
        sb.append("    correlationGuid: ")
                .append(toIndentedString(correlationGuid))
                .append("\n");
        sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `description` to the URL query string
        if (getDescription() != null) {
            joiner.add(getDescription().toUrlQueryString(prefix + "description" + suffix));
        }

        // add `id` to the URL query string
        if (getId() != null) {
            joiner.add(String.format(
                    "%sid%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getId()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `guid` to the URL query string
        if (getGuid() != null) {
            joiner.add(String.format(
                    "%sguid%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getGuid()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `correlationGuid` to the URL query string
        if (getCorrelationGuid() != null) {
            joiner.add(String.format(
                    "%scorrelationGuid%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getCorrelationGuid()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `properties` to the URL query string
        if (getProperties() != null) {
            joiner.add(String.format(
                    "%sproperties%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getProperties()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        return joiner.toString();
    }
}
