/*
 * HiddenLayer ModelScan V2
 * HiddenLayer ModelScan API for scanning of models
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * ValidationErrorModel
 */
@JsonPropertyOrder({
    ValidationErrorModel.JSON_PROPERTY_LOC,
    ValidationErrorModel.JSON_PROPERTY_MSG,
    ValidationErrorModel.JSON_PROPERTY_TYPE
})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2024-12-03T15:49:05.899737Z[GMT]",
        comments = "Generator version: 7.6.0")
public class ValidationErrorModel {
    public static final String JSON_PROPERTY_LOC = "loc";
    private List<LocationInner> loc = new ArrayList<>();

    public static final String JSON_PROPERTY_MSG = "msg";
    private String msg;

    public static final String JSON_PROPERTY_TYPE = "type";
    private String type;

    public ValidationErrorModel() {}

    public ValidationErrorModel loc(List<LocationInner> loc) {
        this.loc = loc;
        return this;
    }

    public ValidationErrorModel addLocItem(LocationInner locItem) {
        if (this.loc == null) {
            this.loc = new ArrayList<>();
        }
        this.loc.add(locItem);
        return this;
    }

    /**
     * Get loc
     * @return loc
     **/
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_LOC)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public List<LocationInner> getLoc() {
        return loc;
    }

    @JsonProperty(JSON_PROPERTY_LOC)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLoc(List<LocationInner> loc) {
        this.loc = loc;
    }

    public ValidationErrorModel msg(String msg) {
        this.msg = msg;
        return this;
    }

    /**
     * Get msg
     * @return msg
     **/
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_MSG)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getMsg() {
        return msg;
    }

    @JsonProperty(JSON_PROPERTY_MSG)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setMsg(String msg) {
        this.msg = msg;
    }

    public ValidationErrorModel type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * @return type
     **/
    @javax.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Return true if this ValidationErrorModel object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ValidationErrorModel validationErrorModel = (ValidationErrorModel) o;
        return Objects.equals(this.loc, validationErrorModel.loc)
                && Objects.equals(this.msg, validationErrorModel.msg)
                && Objects.equals(this.type, validationErrorModel.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(loc, msg, type);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ValidationErrorModel {\n");
        sb.append("    loc: ").append(toIndentedString(loc)).append("\n");
        sb.append("    msg: ").append(toIndentedString(msg)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `loc` to the URL query string
        if (getLoc() != null) {
            for (int i = 0; i < getLoc().size(); i++) {
                if (getLoc().get(i) != null) {
                    joiner.add(getLoc().get(i)
                            .toUrlQueryString(String.format(
                                    "%sloc%s%s",
                                    prefix,
                                    suffix,
                                    "".equals(suffix)
                                            ? ""
                                            : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
                }
            }
        }

        // add `msg` to the URL query string
        if (getMsg() != null) {
            joiner.add(String.format(
                    "%smsg%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getMsg()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `type` to the URL query string
        if (getType() != null) {
            joiner.add(String.format(
                    "%stype%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getType()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        return joiner.toString();
    }
}
