/*
 * HiddenLayer ModelScan V2
 * HiddenLayer ModelScan API for scanning of models
 *
 * The version of the OpenAPI document: 1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Describes an HTTP request.
 */
@JsonPropertyOrder({
    WebRequest.JSON_PROPERTY_INDEX,
    WebRequest.JSON_PROPERTY_PROTOCOL,
    WebRequest.JSON_PROPERTY_VERSION,
    WebRequest.JSON_PROPERTY_TARGET,
    WebRequest.JSON_PROPERTY_METHOD,
    WebRequest.JSON_PROPERTY_HEADERS,
    WebRequest.JSON_PROPERTY_PARAMETERS,
    WebRequest.JSON_PROPERTY_BODY,
    WebRequest.JSON_PROPERTY_PROPERTIES
})
@javax.annotation.Generated(
        value = "org.openapitools.codegen.languages.JavaClientCodegen",
        date = "2024-12-03T15:49:05.899737Z[GMT]",
        comments = "Generator version: 7.6.0")
public class WebRequest {
    public static final String JSON_PROPERTY_INDEX = "index";
    private Integer index = -1;

    public static final String JSON_PROPERTY_PROTOCOL = "protocol";
    private String protocol;

    public static final String JSON_PROPERTY_VERSION = "version";
    private String version;

    public static final String JSON_PROPERTY_TARGET = "target";
    private String target;

    public static final String JSON_PROPERTY_METHOD = "method";
    private String method;

    public static final String JSON_PROPERTY_HEADERS = "headers";
    private Map<String, String> headers = new HashMap<>();

    public static final String JSON_PROPERTY_PARAMETERS = "parameters";
    private Map<String, String> parameters = new HashMap<>();

    public static final String JSON_PROPERTY_BODY = "body";
    private ArtifactContent body;

    public static final String JSON_PROPERTY_PROPERTIES = "properties";
    private PropertyBag properties;

    public WebRequest() {}

    public WebRequest index(Integer index) {
        this.index = index;
        return this;
    }

    /**
     * The index within the run.webRequests array of the request object associated with this result.
     * minimum: -1
     * @return index
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getIndex() {
        return index;
    }

    @JsonProperty(JSON_PROPERTY_INDEX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIndex(Integer index) {
        this.index = index;
    }

    public WebRequest protocol(String protocol) {
        this.protocol = protocol;
        return this;
    }

    /**
     * The request protocol. Example: &#39;http&#39;.
     * @return protocol
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROTOCOL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getProtocol() {
        return protocol;
    }

    @JsonProperty(JSON_PROPERTY_PROTOCOL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public WebRequest version(String version) {
        this.version = version;
        return this;
    }

    /**
     * The request version. Example: &#39;1.1&#39;.
     * @return version
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_VERSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getVersion() {
        return version;
    }

    @JsonProperty(JSON_PROPERTY_VERSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVersion(String version) {
        this.version = version;
    }

    public WebRequest target(String target) {
        this.target = target;
        return this;
    }

    /**
     * The target of the request.
     * @return target
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TARGET)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getTarget() {
        return target;
    }

    @JsonProperty(JSON_PROPERTY_TARGET)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTarget(String target) {
        this.target = target;
    }

    public WebRequest method(String method) {
        this.method = method;
        return this;
    }

    /**
     * The HTTP method. Well-known values are &#39;GET&#39;, &#39;PUT&#39;, &#39;POST&#39;, &#39;DELETE&#39;, &#39;PATCH&#39;, &#39;HEAD&#39;, &#39;OPTIONS&#39;, &#39;TRACE&#39;, &#39;CONNECT&#39;.
     * @return method
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_METHOD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getMethod() {
        return method;
    }

    @JsonProperty(JSON_PROPERTY_METHOD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMethod(String method) {
        this.method = method;
    }

    public WebRequest headers(Map<String, String> headers) {
        this.headers = headers;
        return this;
    }

    public WebRequest putHeadersItem(String key, String headersItem) {
        if (this.headers == null) {
            this.headers = new HashMap<>();
        }
        this.headers.put(key, headersItem);
        return this;
    }

    /**
     * The request headers.
     * @return headers
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_HEADERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, String> getHeaders() {
        return headers;
    }

    @JsonProperty(JSON_PROPERTY_HEADERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHeaders(Map<String, String> headers) {
        this.headers = headers;
    }

    public WebRequest parameters(Map<String, String> parameters) {
        this.parameters = parameters;
        return this;
    }

    public WebRequest putParametersItem(String key, String parametersItem) {
        if (this.parameters == null) {
            this.parameters = new HashMap<>();
        }
        this.parameters.put(key, parametersItem);
        return this;
    }

    /**
     * The request parameters.
     * @return parameters
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PARAMETERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, String> getParameters() {
        return parameters;
    }

    @JsonProperty(JSON_PROPERTY_PARAMETERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setParameters(Map<String, String> parameters) {
        this.parameters = parameters;
    }

    public WebRequest body(ArtifactContent body) {
        this.body = body;
        return this;
    }

    /**
     * Get body
     * @return body
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_BODY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public ArtifactContent getBody() {
        return body;
    }

    @JsonProperty(JSON_PROPERTY_BODY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBody(ArtifactContent body) {
        this.body = body;
    }

    public WebRequest properties(PropertyBag properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get properties
     * @return properties
     **/
    @javax.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public PropertyBag getProperties() {
        return properties;
    }

    @JsonProperty(JSON_PROPERTY_PROPERTIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProperties(PropertyBag properties) {
        this.properties = properties;
    }

    /**
     * Return true if this webRequest object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WebRequest webRequest = (WebRequest) o;
        return Objects.equals(this.index, webRequest.index)
                && Objects.equals(this.protocol, webRequest.protocol)
                && Objects.equals(this.version, webRequest.version)
                && Objects.equals(this.target, webRequest.target)
                && Objects.equals(this.method, webRequest.method)
                && Objects.equals(this.headers, webRequest.headers)
                && Objects.equals(this.parameters, webRequest.parameters)
                && Objects.equals(this.body, webRequest.body)
                && Objects.equals(this.properties, webRequest.properties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(index, protocol, version, target, method, headers, parameters, body, properties);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class WebRequest {\n");
        sb.append("    index: ").append(toIndentedString(index)).append("\n");
        sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
        sb.append("    version: ").append(toIndentedString(version)).append("\n");
        sb.append("    target: ").append(toIndentedString(target)).append("\n");
        sb.append("    method: ").append(toIndentedString(method)).append("\n");
        sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
        sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
        sb.append("    body: ").append(toIndentedString(body)).append("\n");
        sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert the instance into URL query string.
     *
     * @return URL query string
     */
    public String toUrlQueryString() {
        return toUrlQueryString(null);
    }

    /**
     * Convert the instance into URL query string.
     *
     * @param prefix prefix of the query string
     * @return URL query string
     */
    public String toUrlQueryString(String prefix) {
        String suffix = "";
        String containerSuffix = "";
        String containerPrefix = "";
        if (prefix == null) {
            // style=form, explode=true, e.g. /pet?name=cat&type=manx
            prefix = "";
        } else {
            // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
            prefix = prefix + "[";
            suffix = "]";
            containerSuffix = "]";
            containerPrefix = "[";
        }

        StringJoiner joiner = new StringJoiner("&");

        // add `index` to the URL query string
        if (getIndex() != null) {
            joiner.add(String.format(
                    "%sindex%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getIndex()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `protocol` to the URL query string
        if (getProtocol() != null) {
            joiner.add(String.format(
                    "%sprotocol%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getProtocol()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `version` to the URL query string
        if (getVersion() != null) {
            joiner.add(String.format(
                    "%sversion%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getVersion()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `target` to the URL query string
        if (getTarget() != null) {
            joiner.add(String.format(
                    "%starget%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getTarget()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `method` to the URL query string
        if (getMethod() != null) {
            joiner.add(String.format(
                    "%smethod%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getMethod()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        // add `headers` to the URL query string
        if (getHeaders() != null) {
            for (String _key : getHeaders().keySet()) {
                joiner.add(String.format(
                        "%sheaders%s%s=%s",
                        prefix,
                        suffix,
                        "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
                        getHeaders().get(_key),
                        URLEncoder.encode(String.valueOf(getHeaders().get(_key)), StandardCharsets.UTF_8)
                                .replaceAll("\\+", "%20")));
            }
        }

        // add `parameters` to the URL query string
        if (getParameters() != null) {
            for (String _key : getParameters().keySet()) {
                joiner.add(String.format(
                        "%sparameters%s%s=%s",
                        prefix,
                        suffix,
                        "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
                        getParameters().get(_key),
                        URLEncoder.encode(String.valueOf(getParameters().get(_key)), StandardCharsets.UTF_8)
                                .replaceAll("\\+", "%20")));
            }
        }

        // add `body` to the URL query string
        if (getBody() != null) {
            joiner.add(getBody().toUrlQueryString(prefix + "body" + suffix));
        }

        // add `properties` to the URL query string
        if (getProperties() != null) {
            joiner.add(String.format(
                    "%sproperties%s=%s",
                    prefix,
                    suffix,
                    URLEncoder.encode(String.valueOf(getProperties()), StandardCharsets.UTF_8)
                            .replaceAll("\\+", "%20")));
        }

        return joiner.toString();
    }
}
